name: CI

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      
      - name: Install Pandoc
        run: |
          curl -sSL https://github.com/jgm/pandoc/releases/download/3.1.3/pandoc-3.1.3-1-amd64.deb --output pandoc.deb
          sudo dpkg -i pandoc.deb

      - name: Enable Homebrew
        uses: raviqqe/enable-homebrew@v0.1.0
          
      - name: Install pandoc and utils with brew
        run: brew install pandoc-crossref
        
      - name: Install other utils
        run: sudo apt install pandoc-citeproc texlive-xetex texlive-lang-cyrillic fonts-cmu
      
      - name: Get Zotero Group Library
          steps:
            - name: Make HTTP request
              id: http_request
              uses: jakejarvis/http-requests@master
              with:
                method: GET
                url: https://api.zotero.org/groups/5103907/items?key=ivTo6fvNvbU1MEduQJQENgmi
                headers: |
                  Accept: application/json

            - name: Save response to JSON file
              run: |
              cd service
              echo "${{ steps.http_request.outputs.response }}" > zotero-library.json

      - name: Compile
        run: |
          pandoc \
          --pdf-engine=xelatex \
          -V mainfont="CMU Serif" \
          -V monofont="CMU Typewriter Text" \
          --toc \
          --toc-depth=2 \
          --filter=pandoc-crossref \
          --csl=service/apa.csl \
          --metadata-file=text/000_metadata.md \
          --bibliography=service/zotero-library.json \
          --resource-path=images \
          --number-sections \
          --citeproc \
          --output=report.pdf text/*.md
      
      - name: Delete pandoc.deb
        run: sudo rm pandoc.deb
      
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: Changed files
